[project]
name = "countdown-timer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[tool.ruff]
line-length = 120	
select = ['E', 'F', 'W', 'A', 'PLC', 'PLE', 'PLW', 'I']
